add metadata on schema
initia-labs/initia-registry pull request #8
Opened 2024-02-28 06:06 UTC by JSHan94

2024-02-28 06:51 UTC, Vritra4 commented
is it valid? seems very different with other properties

2024-02-28 07:27 UTC, Vritra4 commented on chain.schema.json
> +        "faucet-api": {
why faucet-api instead of faucet?

2024-02-28 07:35 UTC, Vritra4 commented on chain.schema.json
> +          "items": {
how about moving into defs and using refs to the def?
then we can use regex to validate its denom and mount.

2024-02-28 07:44 UTC, Vritra4 commented on chain.schema.json
> +          "items": {
denom: `[a-zA-Z][a-zA-Z0-9/:._-]{2,127}`
amount: `[[:digit:]]+`
decAmount: `[[:digit:]]+(?:\.[[:digit:]]+)?|\.[[:digit:]]+`

2024-02-28 08:40 UTC, JSHan94 commented on chain.schema.json
> +          "items": {
in origin schema, `free_token` or `staking_token` is just like below
```
"staking_token": {
      "type": "object",
      "required": [
        "denom"
      ],
      "properties": {
        "denom": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
 ```

so i wonder whether we should support regex for denom.

2024-02-28 08:56 UTC, Vritra4 commented on chain.schema.json
> +          "items": {
so your opinion is invalid denom is okay? i don't think so.
I think we should test them too because more validation ensures higher integrity.

2024-02-28 09:33 UTC, JSHan94 commented on chain.schema.json
> +          "items": {
added coin, amount, denom defs

2024-02-28 09:59 UTC, Vritra4 approved these changes
LGTM
@beer-1 please review this PR :) i think crossreview from you would be nice

2024-02-29 06:11 UTC, beer-1 commented on chain.schema.json
> +          "description": "[Optional] The list of denoms and their respective amounts that are allowed to be transferred without fees."
A list that outlines various coin amounts. Each coin amount, denoted by the denomination (denom) and the amount, establishes a balance threshold where transaction fees are exempted. If a user's balance meets or surpasses any of these coin amounts, transaction fees will not be applied.

2024-02-29 06:11 UTC, beer-1 commented on devnets/mahalo/assetlist.json
> +          "png": "https://raw.githubusercontent.com/initia-labs/initia-registry/main/devnets/mahalo/images/ETH-INIT.png",
ETH-INIT => INIT

2024-02-29 06:11 UTC, beer-1 commented on chain.schema.json
> +        "faucet": {
This seems saying faucet site not faucet api. 
how about change this to `faucet_api`?

2024-02-29 06:16 UTC, simcheolhwan requested changes

2024-02-29 06:16 UTC, simcheolhwan commented on chain.schema.json
> +      "pattern": "[[:digit:]]+"
please use 0-9 for general usage :)

2024-02-29 06:17 UTC, Vritra4 commented on chain.schema.json
> +        "faucet": {
afaik faucet-api won't be exposed to public

2024-02-29 06:19 UTC, simcheolhwan commented on chain.schema.json
> +        "faucet": {
because the object key is `apis` (not `urls`) so i think `faucet` means the `faucet api` already.

2024-02-29 06:19 UTC, simcheolhwan commented on chain.schema.json
> +        "faucet": {
any thought? @Vritra4

2024-02-29 06:26 UTC, Vritra4 commented on chain.schema.json
> +        "faucet": {
let's move it to next to explorer as we discussed lol

2024-02-29 06:27 UTC, Vritra4 commented on chain.schema.json
> +        "faucet": {
@JSHan94 and fix values of faucet. no -api.

2024-02-29 06:27 UTC, simcheolhwan commented on chain.schema.json
> +        "faucet": {
we decided to remove `faucet api` from the schema and add `faucet websites` in the same depth with `explorers`

2024-02-29 06:27 UTC, simcheolhwan commented on chain.schema.json
> +        "faucet": {
like `faucets`?

2024-02-29 06:29 UTC, Vritra4 commented on chain.schema.json
> +        "faucet": {
i agree

2024-02-29 06:30 UTC, Vritra4 commented on chain.schema.json
> +      "pattern": "[[:digit:]]+"
i can't agree more lol

2024-02-29 06:40 UTC, JSHan94 commented on chain.schema.json
> +          "description": "[Optional] The list of denoms and their respective amounts that are allowed to be transferred without fees."
rewrite description like `A list specifying coin amounts by denomination that exempt users from transaction fees when their balance meets or exceeds these amounts.`

2024-02-29 06:47 UTC, JSHan94 commented on chain.schema.json
> +        "faucet": {
fixed

2024-02-29 07:00 UTC, Vritra4 commented on chain.schema.json
> +        "faucet": {
i think we need to add `"additionalProperties": false` into $defs/faucet.

2024-02-29 07:02 UTC, Vritra4 commented on chain.schema.json
> +    },
i think we need to add "additionalProperties": false into $defs/faucet unless you are intended to allow additional properties.

2024-02-29 07:07 UTC, Vritra4 commented on chain.schema.json
> +    },
so we need wrap regexes with ^ and $

2024-02-29 13:02 UTC, simcheolhwan approved these changes

2024-02-29 13:09 UTC, merged